- name: Install drush for command-line managing Drupal sites
  apt: pkg=drush
  sudo: yes

- name: Clone/update Drush git repository to /usr/local/share/drush and checkout master branch on it
  git:
    repo='https://github.com/drush-ops/drush.git'
    dest=/usr/local/share/drush
  sudo: yes

- name: Install/Update Drush components (now with composer)
  shell:
    cd /usr/local/share/drush/ && composer install
  sudo: yes

- name: Create symlink to the latest drush
  file:
    src=/usr/local/share/drush/drush
    path=/usr/local/bin/drush
    state=link
  sudo: yes
